name: todos
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  font_awesome_flutter: ^10.1.0

#  firebase_integration:
#    hosted: https://artalaxies.jfrog.io/artifactory/api/pub/artalaxies-pub-dev
#    version: ^0.0.1+1
#
#  web3_utility:
#    hosted: https://artalaxies.jfrog.io/artifactory/api/pub/artalaxies-pub-dev
#    version: ^0.0.1+1
#
#  multilayer_framework:
#    hosted: https://artalaxies.jfrog.io/artifactory/api/pub/artalaxies-pub-dev
#    version: ^0.1.1
#
#  cullen_utilities:
#    hosted: https://artalaxies.jfrog.io/artifactory/api/pub/artalaxies-pub-dev
#    version: ^0.1.2
#  syncfusion_flutter_charts: ^19.3.48

  web_socket_channel: ^2.1.0
#  wallet_connect: ^1.0.4
#  web3dart: ^2.5.2
#  walletconnect_dart: ^0.0.11
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  replay_bloc: ^0.2.2
  flow_builder: ^0.0.9

  json_annotation: ^4.7.0

  go_router: ^6.0.0
  fpdart: ^0.4.0
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15

  server_storage_todos_api_impl:
    path: packages/todos/server_storage_todos_api_impl
  form_inputs:
    path: packages/authentication/form_inputs
  authentication_repository:
    path: packages/authentication/authentication_repository
  todos_repository:
    path: packages/todos/todos_repository

#dependency_overrides:

#  unofficial_notionapi:
#    git:
#      url: git://github.com/NumFlurry/Unofficial-Notion-API-V3---Dart.git
#  stream_channel: ^2.1.1
#  collection: ^1.17.0
#  async: ^2.10.0
  #  universal_html: ^2.0.8
  #  universal_io: ^2.0.4
#  flutter_widget_from_html: ^0.6.1
#  http: ^0.13.3
#  shared_preferences: ^2.0.6

  #  timeline_tile: ^1.0.0
  #  js: ^0.6.2

  #networking
  #  http: ^0.12.2
  #  json_annotation: ^4.0.1
  #  json_serializable: ^4.1.3
#  url_launcher: ^6.0.4
#
#  flutter_linkify: ^5.0.2

#  draggable_scrollbar: ^0.1.0
  #  flutter_highlight: ^0.6.0
  #  url_strategy: ^0.2.0


  #  xml2json: ^5.2.0
  #  get_it: ^7.1.3
#  after_layout: ^1.1.0
  #  stacked: ^1.7.7

#  devicelocale: ^0.4.1

  #dash-overflow.net
  #  provider: ^5.0.0

#  auto_size_text: ^3.0.0-nullsafety.0

#  flutter_markdown: ^0.6.6
  pointer_interceptor: ^0.9.0+1

#  webview_flutter: ^2.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.2
#  google_fonts: ^1.1.1
#  weather_icons: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  bloc_test: ^9.1.0
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets: [ images/ ]
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  generate: true